Document: deb-release
Title: Debian deb-release Manual
Author: <insert document author here>
Abstract: This manual describes what deb-release is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/deb-release/deb-release.sgml.gz

Format: postscript
Files: /usr/share/doc/deb-release/deb-release.ps.gz

Format: text
Files: /usr/share/doc/deb-release/deb-release.text.gz

Format: HTML
Index: /usr/share/doc/deb-release/html/index.html
Files: /usr/share/doc/deb-release/html/*.html
